version: '3.3'

services:

    elasticsearch:
        image: elasticsearch
        ports:
            - 9200:9200
        volumes:
          - elastic-vol:/usr/share/elasticsearch/data

    kibana:
        image: kibana
        ports:
            - 5601:5601

volumes:
  elastic-vol:
